In [40]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

import pandas as pd
pd.options.display.max_rows = 999
import gc
import numpy as np
#import cudf
from glob import glob
from tqdm import tqdm
import gc
#import cudf



In [41]:
df = pd.read_csv('OTTO.csv')

C:\Users\win10\AppData\Local\Temp/ipykernel_108/1676143532.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('OTTO.csv')


In [42]:
df

Unnamed: 0   session      aid          ts  type
0        Unnamed: 0         0        1           2     3
1                 0  11098528    11830  1661119200     0
2                 1  11098529  1105029  1661119200     0
3                 2  11098530   264500  1661119200     0
4                 3  11098530   264500  1661119288     0
...             ...       ...      ...         ...   ...
7683573     7683572  12899774    33035  1661723968     0
7683574     7683573  12899775  1743151  1661723970     0
7683575     7683574  12899776   548599  1661723972     0
7683576     7683575  12899777   384045  1661723976     0
7683577     7683576  12899778   561560  1661723983     0

[7683578 rows x 5 columns]

In [43]:
df['session'].value_counts()


11150244    465
12224837    422
11886540    366
12238424    355
11831609    355
           ... 
11944124      1
11944126      1
11944127      1
11944128      1
12899778      1
Name: session, Length: 1801252, dtype: int64

In [44]:
df['aid'].value_counts().head(20)

485256     36584
1460571     8008
33343       7198
613493      6616
108125      6073
876493      5847
152547      5807
1551213     5642
1406660     4336
1236775     4293
184976      4168
836852      3857
1531805     3776
331708      3624
29735       3567
554660      3320
634452      3271
986164      3168
832192      3121
166037      3076
Name: aid, dtype: int64

In [45]:
df['type'].value_counts()

0    6958277
1     650768
2      74532
3          1
Name: type, dtype: int64

In [46]:
import numpy as np
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
# from google.cloud import storage
#import polars as pl
#import gc



In [47]:
df['ts']= pd.to_datetime(df['ts'], unit='s')


In [48]:
df['year'] = pd.DatetimeIndex(df['ts']).year
#df['year'] = pd.DatetimeIndex(df['birth_date']).year

df['month'] = pd.DatetimeIndex(df['ts']).month
df['Day'] = pd.DatetimeIndex(df['ts']).day

In [49]:
df['year'].unique()

array([1970, 2022], dtype=int64)

In [50]:
df['month'].unique()

array([1, 8], dtype=int64)

In [51]:
df['Day'].unique()

array([ 1, 21, 22, 23, 24, 26, 28, 27, 25], dtype=int64)

In [52]:
df

Unnamed: 0   session      aid                  ts  type  year  month  \
0        Unnamed: 0         0        1 1970-01-01 00:00:02     3  1970      1   
1                 0  11098528    11830 2022-08-21 22:00:00     0  2022      8   
2                 1  11098529  1105029 2022-08-21 22:00:00     0  2022      8   
3                 2  11098530   264500 2022-08-21 22:00:00     0  2022      8   
4                 3  11098530   264500 2022-08-21 22:01:28     0  2022      8   
...             ...       ...      ...                 ...   ...   ...    ...   
7683573     7683572  12899774    33035 2022-08-28 21:59:28     0  2022      8   
7683574     7683573  12899775  1743151 2022-08-28 21:59:30     0  2022      8   
7683575     7683574  12899776   548599 2022-08-28 21:59:32     0  2022      8   
7683576     7683575  12899777   384045 2022-08-28 21:59:36     0  2022      8   
7683577     7683576  12899778   561560 2022-08-28 21:59:43     0  2022      8   

         Day  
0          1  
1         21  
2         21  
3         21  
4         21  
...      ...  
7683573   28  
7683574   28  
7683575   28  
7683576   28  
7683577   28  

[7683578 rows x 8 columns]

In [53]:
type_0 = df['type'] == 0
type_0

0          False
1           True
2           True
3           True
4           True
           ...  
7683573     True
7683574     True
7683575     True
7683576     True
7683577     True
Name: type, Length: 7683578, dtype: bool

In [54]:
type_1 = df['type'] == 1
type_1

0          False
1          False
2          False
3          False
4          False
           ...  
7683573    False
7683574    False
7683575    False
7683576    False
7683577    False
Name: type, Length: 7683578, dtype: bool

In [55]:
type_2  = df['type'] == 2
type_2

0          False
1          False
2          False
3          False
4          False
           ...  
7683573    False
7683574    False
7683575    False
7683576    False
7683577    False
Name: type, Length: 7683578, dtype: bool

In [56]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

import pandas as pd
pd.options.display.max_rows = 999
import gc
import numpy as np
import cudf
from glob import glob
from tqdm import tqdm
import gc
import cudf

ModuleNotFoundError: No module named 'cudf'

In [57]:
#train = cudf.read_parquet('../input/train.parquet')
test = pd.read_csv('OTTO.csv')

#train = train.sort_values(['session', 'ts', 'type'], ascending=[True, False, True]).reset_index(drop=True)
#train['n'] = train.groupby('session')['ts'].cumcount()
test = test.sort_values(['session', 'ts', 'type'], ascending=[True, False, True]).reset_index(drop=True)
test['n'] = test.groupby('session')['ts'].cumcount()

print(test.shape)

#train['ts'] = train['ts'].astype('int64') // 1000000
test['ts'] = test['ts'].astype('int64') // 1000000
#freemem(train)
#freemem(test)
gc.collect()

C:\Users\win10\AppData\Local\Temp/ipykernel_108/3107583915.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  test = pd.read_csv('OTTO.csv')


(7683578, 6)


76

In [58]:
test

Unnamed: 0   session      aid    ts  type  n
0        Unnamed: 0         0        1     0     3  0
1                 0  11098528    11830  1661     0  0
2                 1  11098529  1105029  1661     0  0
3                 7  11098530   409236  1661     1  0
4                 6  11098530   409236  1661     0  1
...             ...       ...      ...   ...   ... ..
7683573     7683572  12899774    33035  1661     0  0
7683574     7683573  12899775  1743151  1661     0  0
7683575     7683574  12899776   548599  1661     0  0
7683576     7683575  12899777   384045  1661     0  0
7683577     7683576  12899778   561560  1661     0  0

[7683578 rows x 6 columns]

In [59]:
dt = test.groupby('session')['aid'].count()
dt = dt[dt>=2]
dt = dt.sort_values().reset_index()
dt = dt.loc[((dt['session'] % 10)==0) & (dt['aid']>=2) ]
print(dt.shape)
dt.tail(5)

(100185, 2)


session  aid
1001303  11786420  293
1001308  12202120  298
1001309  11278970  299
1001323  11222220  350
1001326  11886540  366

In [60]:
valid = test.loc[test.session.isin(dt['session']) ].reset_index(drop=True)
test = test.loc[test.session.isin(dt['session']) ].reset_index(drop=True)

valid.shape, test.shape

((695259, 6), (695259, 6))

In [61]:
valid

Unnamed: 0   session      aid    ts  type  n
0               7  11098530   409236  1661     1  0
1               6  11098530   409236  1661     0  1
2               5  11098530   409236  1661     0  2
3               4  11098530   409236  1661     0  3
4               3  11098530   264500  1661     0  4
...           ...       ...      ...   ...   ... ..
695254    7683296  12899580  1604220  1661     0  1
695255    7683328  12899600  1409732  1661     0  0
695256    7683327  12899600  1022807  1661     0  1
695257    7683347  12899610   527101  1661     0  0
695258    7683346  12899610  1406630  1661     0  1

[695259 rows x 6 columns]

In [62]:
test[f'ts_diff'] = test.groupby('session')['ts'].shift(1).fillna(0).astype('int32')
test[f'ts_diff'] = (test[f'ts'] - test[f'ts_diff'])
test[f'ts_diff'] = test[f'ts_diff'].clip(0, 24*60*60)
test.loc[test.ts_diff<2*60*60 , f'ts_diff'] = 0
test.loc[test.ts_diff>=2*60*60 , f'ts_diff'] = 1
gc.collect()
test[f'subses'] = test.groupby('session')['ts_diff'].cumsum()
test[f'subses'] = (test[f'session']*128 + test[f'subses']).factorize()[0]
print(test[f'ts_diff'].mean())
test.head(2)


0.0


Unnamed: 0   session     aid    ts  type  n  ts_diff  subses
0          7  11098530  409236  1661     1  0        0       0
1          6  11098530  409236  1661     0  1        0       0

In [63]:
 

#def freemem(df):
    #for col in df.columns:
        #if df[col].dtype == 'int64':
            #df[col] = df[col].astype('int32')
        #elif df[col].dtype == 'float64':
            #df[col] = df[col].astype('float32')
    #gc.collect()
    #return

#device = 'cuda'
#USE_GPU = torch.cuda.is_available()
#print('Is GPU available?', USE_GPU)

In [64]:
#for lag in range(11):
    #test[f'lag{lag}'] = test.groupby('subses')['aid'].shift(lag).fillna(-1).astype('int32')
    #gc.collect()
    
#del test['aid']
#gc.collect()
#freemem(test); gc.collect()

#test.head(6)

In [65]:
#print(test.shape)
#del test['ts_diff']; gc.collect()

#test = test.loc[(test['type'] == 0) & (test['lag1'] >= 0)].reset_index(drop=True)
#del test['type']
#gc.collect()

#print(test.shape)
#test.head(6)

In [66]:
#test['hour'] = ((test['ts']-test['ts'].min()) // (8*60*60)).astype('int8') 
#del test['ts'], test['subses']
#gc.collect()
#test.tail(2)

In [67]:
#test['hour'].max()


In [ ]:
test[f'ts_diff'] = test.groupby('session')['ts'].shift(1).fillna(0).astype('int32')
test[f'ts_diff'] = (test[f'ts'] - test[f'ts_diff'])
test[f'ts_diff'] = test[f'ts_diff'].clip(0, 24*60*60)
test.loc[test.ts_diff<2*60*60 , f'ts_diff'] = 0
test.loc[test.ts_diff>=2*60*60 , f'ts_diff'] = 1
gc.collect()
test[f'subses'] = test.groupby('session')['ts_diff'].cumsum()
test[f'subses'] = (test[f'session']*128 + test[f'subses']).factorize()[0]
print(test[f'ts_diff'].mean())
test.head(2)

In [71]:
test[f'ts_diff'] = test.groupby('session')['ts'].shift(1).fillna(0).astype('int32')
test[f'ts_diff'] = (test[f'ts'] - test[f'ts_diff'])
test[f'ts_diff'] = test[f'ts_diff'].clip(0, 24*60*60)
test[f'ts_diff']


0         1661
1            0
2            0
3            0
4            0
          ... 
695254       0
695255    1661
695256       0
695257    1661
695258       0
Name: ts_diff, Length: 695259, dtype: int64

In [72]:
r = test.loc[test.ts_diff<2*60*60 , f'ts_diff'] = 0
r

0

In [73]:
 test.loc[test.ts_diff>=2*60*60 , f'ts_diff'] = 1
gc.collect()

0

In [75]:
test[f'subses'] = test.groupby('session')['ts_diff'].cumsum()
test[f'subses'].unique()

array([0], dtype=int64)

In [76]:
test[f'subses'] = (test[f'session']*128 + test[f'subses']).factorize()[0]
print(test[f'ts_diff'].mean())
test.head(2)

0.0


Unnamed: 0   session     aid    ts  type  n  ts_diff  subses
0          7  11098530  409236  1661     1  0        0       0
1          6  11098530  409236  1661     0  1        0       0